package cn.urbanwall.dao;
import cn.urbanwall.model.TbCollectProduct;
import cn.urbanwall.model.TbCollectProductExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbCollectProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    int countByExample(TbCollectProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    int deleteByExample(TbCollectProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long colId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    int insert(TbCollectProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    int insertSelective(TbCollectProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    List<TbCollectProduct> selectByExample(TbCollectProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    TbCollectProduct selectByPrimaryKey(Long colId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbCollectProduct record, @Param("example") TbCollectProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbCollectProduct record, @Param("example") TbCollectProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbCollectProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbCollectProduct record);
}