package cn.urbanwall.dao;

import java.util.List;

import cn.urbanwall.model.TbLikeProduct;
import cn.urbanwall.model.TbLikeProductExample;
import org.apache.ibatis.annotations.Param;

public interface TbLikeProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_like_product
     *
     * @mbggenerated
     */
    int countByExample(TbLikeProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_like_product
     *
     * @mbggenerated
     */
    int deleteByExample(TbLikeProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_like_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_like_product
     *
     * @mbggenerated
     */
    int insert(TbLikeProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_like_product
     *
     * @mbggenerated
     */
    int insertSelective(TbLikeProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_like_product
     *
     * @mbggenerated
     */
    List<TbLikeProduct> selectByExample(TbLikeProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_like_product
     *
     * @mbggenerated
     */
    TbLikeProduct selectByPrimaryKey(Long likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_like_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbLikeProduct record, @Param("example") TbLikeProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_like_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbLikeProduct record, @Param("example") TbLikeProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_like_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbLikeProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_like_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbLikeProduct record);
}