package cn.urbanwall.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_comment_product
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class TbCommentProduct {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_product.com_id
     *
     * @mbggenerated
     */
    private Long comId;

    /**
     * Database Column Remarks:
     *   父id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_product.com_parends
     *
     * @mbggenerated
     */
    private Long comParends;

    /**
     * Database Column Remarks:
     *   评论内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_product.com_content
     *
     * @mbggenerated
     */
    private String comContent;

    /**
     * Database Column Remarks:
     *   发布人的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_product.com_user_id
     *
     * @mbggenerated
     */
    private String comUserId;

    /**
     * Database Column Remarks:
     *   发布时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_product.com_time
     *
     * @mbggenerated
     */
    private Date comTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_product.com_id
     *
     * @return the value of tb_comment_product.com_id
     *
     * @mbggenerated
     */
    public Long getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_product.com_id
     *
     * @param comId the value for tb_comment_product.com_id
     *
     * @mbggenerated
     */
    public void setComId(Long comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_product.com_parends
     *
     * @return the value of tb_comment_product.com_parends
     *
     * @mbggenerated
     */
    public Long getComParends() {
        return comParends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_product.com_parends
     *
     * @param comParends the value for tb_comment_product.com_parends
     *
     * @mbggenerated
     */
    public void setComParends(Long comParends) {
        this.comParends = comParends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_product.com_content
     *
     * @return the value of tb_comment_product.com_content
     *
     * @mbggenerated
     */
    public String getComContent() {
        return comContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_product.com_content
     *
     * @param comContent the value for tb_comment_product.com_content
     *
     * @mbggenerated
     */
    public void setComContent(String comContent) {
        this.comContent = comContent == null ? null : comContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_product.com_user_id
     *
     * @return the value of tb_comment_product.com_user_id
     *
     * @mbggenerated
     */
    public String getComUserId() {
        return comUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_product.com_user_id
     *
     * @param comUserId the value for tb_comment_product.com_user_id
     *
     * @mbggenerated
     */
    public void setComUserId(String comUserId) {
        this.comUserId = comUserId == null ? null : comUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_product.com_time
     *
     * @return the value of tb_comment_product.com_time
     *
     * @mbggenerated
     */
    public Date getComTime() {
        return comTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_product.com_time
     *
     * @param comTime the value for tb_comment_product.com_time
     *
     * @mbggenerated
     */
    public void setComTime(Date comTime) {
        this.comTime = comTime;
    }
}