package cn.urbanwall.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbCollectProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    public TbCollectProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andColIdIsNull() {
            addCriterion("col_id is null");
            return (Criteria) this;
        }

        public Criteria andColIdIsNotNull() {
            addCriterion("col_id is not null");
            return (Criteria) this;
        }

        public Criteria andColIdEqualTo(Long value) {
            addCriterion("col_id =", value, "colId");
            return (Criteria) this;
        }

        public Criteria andColIdNotEqualTo(Long value) {
            addCriterion("col_id <>", value, "colId");
            return (Criteria) this;
        }

        public Criteria andColIdGreaterThan(Long value) {
            addCriterion("col_id >", value, "colId");
            return (Criteria) this;
        }

        public Criteria andColIdGreaterThanOrEqualTo(Long value) {
            addCriterion("col_id >=", value, "colId");
            return (Criteria) this;
        }

        public Criteria andColIdLessThan(Long value) {
            addCriterion("col_id <", value, "colId");
            return (Criteria) this;
        }

        public Criteria andColIdLessThanOrEqualTo(Long value) {
            addCriterion("col_id <=", value, "colId");
            return (Criteria) this;
        }

        public Criteria andColIdIn(List<Long> values) {
            addCriterion("col_id in", values, "colId");
            return (Criteria) this;
        }

        public Criteria andColIdNotIn(List<Long> values) {
            addCriterion("col_id not in", values, "colId");
            return (Criteria) this;
        }

        public Criteria andColIdBetween(Long value1, Long value2) {
            addCriterion("col_id between", value1, value2, "colId");
            return (Criteria) this;
        }

        public Criteria andColIdNotBetween(Long value1, Long value2) {
            addCriterion("col_id not between", value1, value2, "colId");
            return (Criteria) this;
        }

        public Criteria andColProIdIsNull() {
            addCriterion("col_pro_id is null");
            return (Criteria) this;
        }

        public Criteria andColProIdIsNotNull() {
            addCriterion("col_pro_id is not null");
            return (Criteria) this;
        }

        public Criteria andColProIdEqualTo(Long value) {
            addCriterion("col_pro_id =", value, "colProId");
            return (Criteria) this;
        }

        public Criteria andColProIdNotEqualTo(Long value) {
            addCriterion("col_pro_id <>", value, "colProId");
            return (Criteria) this;
        }

        public Criteria andColProIdGreaterThan(Long value) {
            addCriterion("col_pro_id >", value, "colProId");
            return (Criteria) this;
        }

        public Criteria andColProIdGreaterThanOrEqualTo(Long value) {
            addCriterion("col_pro_id >=", value, "colProId");
            return (Criteria) this;
        }

        public Criteria andColProIdLessThan(Long value) {
            addCriterion("col_pro_id <", value, "colProId");
            return (Criteria) this;
        }

        public Criteria andColProIdLessThanOrEqualTo(Long value) {
            addCriterion("col_pro_id <=", value, "colProId");
            return (Criteria) this;
        }

        public Criteria andColProIdIn(List<Long> values) {
            addCriterion("col_pro_id in", values, "colProId");
            return (Criteria) this;
        }

        public Criteria andColProIdNotIn(List<Long> values) {
            addCriterion("col_pro_id not in", values, "colProId");
            return (Criteria) this;
        }

        public Criteria andColProIdBetween(Long value1, Long value2) {
            addCriterion("col_pro_id between", value1, value2, "colProId");
            return (Criteria) this;
        }

        public Criteria andColProIdNotBetween(Long value1, Long value2) {
            addCriterion("col_pro_id not between", value1, value2, "colProId");
            return (Criteria) this;
        }

        public Criteria andColUserIdIsNull() {
            addCriterion("col_user_id is null");
            return (Criteria) this;
        }

        public Criteria andColUserIdIsNotNull() {
            addCriterion("col_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andColUserIdEqualTo(String value) {
            addCriterion("col_user_id =", value, "colUserId");
            return (Criteria) this;
        }

        public Criteria andColUserIdNotEqualTo(String value) {
            addCriterion("col_user_id <>", value, "colUserId");
            return (Criteria) this;
        }

        public Criteria andColUserIdGreaterThan(String value) {
            addCriterion("col_user_id >", value, "colUserId");
            return (Criteria) this;
        }

        public Criteria andColUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("col_user_id >=", value, "colUserId");
            return (Criteria) this;
        }

        public Criteria andColUserIdLessThan(String value) {
            addCriterion("col_user_id <", value, "colUserId");
            return (Criteria) this;
        }

        public Criteria andColUserIdLessThanOrEqualTo(String value) {
            addCriterion("col_user_id <=", value, "colUserId");
            return (Criteria) this;
        }

        public Criteria andColUserIdLike(String value) {
            addCriterion("col_user_id like", value, "colUserId");
            return (Criteria) this;
        }

        public Criteria andColUserIdNotLike(String value) {
            addCriterion("col_user_id not like", value, "colUserId");
            return (Criteria) this;
        }

        public Criteria andColUserIdIn(List<String> values) {
            addCriterion("col_user_id in", values, "colUserId");
            return (Criteria) this;
        }

        public Criteria andColUserIdNotIn(List<String> values) {
            addCriterion("col_user_id not in", values, "colUserId");
            return (Criteria) this;
        }

        public Criteria andColUserIdBetween(String value1, String value2) {
            addCriterion("col_user_id between", value1, value2, "colUserId");
            return (Criteria) this;
        }

        public Criteria andColUserIdNotBetween(String value1, String value2) {
            addCriterion("col_user_id not between", value1, value2, "colUserId");
            return (Criteria) this;
        }

        public Criteria andColTimeIsNull() {
            addCriterion("col_time is null");
            return (Criteria) this;
        }

        public Criteria andColTimeIsNotNull() {
            addCriterion("col_time is not null");
            return (Criteria) this;
        }

        public Criteria andColTimeEqualTo(Date value) {
            addCriterion("col_time =", value, "colTime");
            return (Criteria) this;
        }

        public Criteria andColTimeNotEqualTo(Date value) {
            addCriterion("col_time <>", value, "colTime");
            return (Criteria) this;
        }

        public Criteria andColTimeGreaterThan(Date value) {
            addCriterion("col_time >", value, "colTime");
            return (Criteria) this;
        }

        public Criteria andColTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("col_time >=", value, "colTime");
            return (Criteria) this;
        }

        public Criteria andColTimeLessThan(Date value) {
            addCriterion("col_time <", value, "colTime");
            return (Criteria) this;
        }

        public Criteria andColTimeLessThanOrEqualTo(Date value) {
            addCriterion("col_time <=", value, "colTime");
            return (Criteria) this;
        }

        public Criteria andColTimeIn(List<Date> values) {
            addCriterion("col_time in", values, "colTime");
            return (Criteria) this;
        }

        public Criteria andColTimeNotIn(List<Date> values) {
            addCriterion("col_time not in", values, "colTime");
            return (Criteria) this;
        }

        public Criteria andColTimeBetween(Date value1, Date value2) {
            addCriterion("col_time between", value1, value2, "colTime");
            return (Criteria) this;
        }

        public Criteria andColTimeNotBetween(Date value1, Date value2) {
            addCriterion("col_time not between", value1, value2, "colTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_collect_product
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_collect_product
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}