package cn.urbanwall.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_like_product
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class TbLikeProduct {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_like_product.like_id
     *
     * @mbggenerated
     */
    private Long likeId;

    /**
     * Database Column Remarks:
     *   喜欢产品的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_like_product.like_pro_id
     *
     * @mbggenerated
     */
    private Long likeProId;

    /**
     * Database Column Remarks:
     *   喜欢的时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_like_product.like_time
     *
     * @mbggenerated
     */
    private Date likeTime;

    /**
     * Database Column Remarks:
     *   用户的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_like_product.like_user_id
     *
     * @mbggenerated
     */
    private String likeUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_like_product.like_id
     *
     * @return the value of tb_like_product.like_id
     *
     * @mbggenerated
     */
    public Long getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_like_product.like_id
     *
     * @param likeId the value for tb_like_product.like_id
     *
     * @mbggenerated
     */
    public void setLikeId(Long likeId) {
        this.likeId = likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_like_product.like_pro_id
     *
     * @return the value of tb_like_product.like_pro_id
     *
     * @mbggenerated
     */
    public Long getLikeProId() {
        return likeProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_like_product.like_pro_id
     *
     * @param likeProId the value for tb_like_product.like_pro_id
     *
     * @mbggenerated
     */
    public void setLikeProId(Long likeProId) {
        this.likeProId = likeProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_like_product.like_time
     *
     * @return the value of tb_like_product.like_time
     *
     * @mbggenerated
     */
    public Date getLikeTime() {
        return likeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_like_product.like_time
     *
     * @param likeTime the value for tb_like_product.like_time
     *
     * @mbggenerated
     */
    public void setLikeTime(Date likeTime) {
        this.likeTime = likeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_like_product.like_user_id
     *
     * @return the value of tb_like_product.like_user_id
     *
     * @mbggenerated
     */
    public String getLikeUserId() {
        return likeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_like_product.like_user_id
     *
     * @param likeUserId the value for tb_like_product.like_user_id
     *
     * @mbggenerated
     */
    public void setLikeUserId(String likeUserId) {
        this.likeUserId = likeUserId == null ? null : likeUserId.trim();
    }
}